#+title: Crab Rangoon Recipe
#+startup: overview

Serves: 12

Prep time: 35 minutes
Cook time: 20 minutes

* Sweet chili dipping sauce:
** Ingredients
+ 1 cup water
+ 1 tablespoon rice vinegar
+ 3 tablespoons ketchup
+ 3 tablespoons sugar
+ 1 tablespoon sambal oelek
+ 3 garlic cloves, minced
+ 1 tablespoon cornstarch
+ 3 tablespoons water
** Instructions
In a saucepan over medium heat, place in the water, rice vinegar, ketchup, sugar, sambal oelek, and garlic.
Bring it to a simmer, and pour in the cornstarch slurry (1 tablespoon of cornstarch and 3 tablespoons of water). Stir until it is thickened. Set aside.

* For the crab rangoon:
** Ingredients
+ 12 wonton wrappers
+ 8 ounces Philadelphia cream cheese
+ 1 1/2 cups crab meat, minced
+ 2 stalk scallions, minced
+ 1 tablespoon soy sauce
+ 1/2 teaspoon sugar
+ Pinch of white pepper
+ 4 cups extra light olive oil, for frying
** Instructions
*** Combine filling
In a mixing bowl, combine the Philadelphia cream cheese, crab meat, scallions, soy sauce, sugar, and white pepper. Mix together.

*** Assemble rangoons
Tap some water on the edges of the wrapper. Place about 1 1/2 teaspoons of filling in the center.
Fold the two ends of the wrapper together, followed by the other two ends, and seal all the edges to form a four-pointed star.

*** Fry the rangoons
In a large pot over high heat, place in the extra light olive oil (or other high smoking point oil of your choice), and heat it to 325°F or 163°C.
Transfer in the crab rangoon, a few at a time. Deep fry until golden brown for about 5 minutes, and turn them frequently so that they brown evenly.
Remove and drain on a paper towel-lined plate. Repeat with the remaining crab rangoon. Serve!
